# Generated by Django 4.2 on 2023-05-05 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/', validators=[organization.models.validate_csv_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('admin_fname', models.CharField(max_length=25)),
                ('admin_lname', models.CharField(max_length=25)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_username', models.CharField(max_length=50, unique=True)),
                ('admin_phone_number', organization.models.NigerianPhoneNumberField(max_length=128, region=None)),
                ('company_email_domain', models.CharField(max_length=20, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobtitles', to='organization.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.organization'),
        ),
    ]
