# Generated by Django 4.2 on 2023-05-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_jobtitle_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='jobtitle',
            old_name='organisation',
            new_name='organization',
        ),
    ]
