# Generated by Django 4.2 on 2023-05-07 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_rename_organisation_department_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='csv_files/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
