# Generated by Django 4.2 on 2023-05-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_slug'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organization.jobtitle'),
        ),
    ]
