# Generated by Django 4.2 on 2023-05-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_slug'),
        ('staff', '0002_alter_staff_dept_alter_staff_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
