# Generated by Django 4.2 on 2023-05-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_rename_organisation_department_organization_and_more'),
        ('staff', '0003_alter_staff_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='employee',
            new_name='staff',
        ),
        migrations.AddField(
            model_name='query',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='organization.jobtitle'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='organization.organization'),
        ),
    ]
