# Generated by Django 4.2 on 2023-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_staff_userprofile_staff_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
