# Generated by Django 4.2 on 2023-05-17 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_department_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0008_alter_staff_work_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='query',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='organization.jobtitle'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile', to='staff.staff'),
        ),
    ]
